<?php
$title = 'Categories';
$this->headTitle($title);
?>

<div class="col-md-6">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <table class="table">
        <tr>
            <th>Titel</th>
        </tr>
        <?php foreach ($categories as $category) : ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('category',
                        array('action'=>'view', 'id' => $category->getId()));?>">
                        <?php echo $this->escapeHtml($category->getTitle())?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="col-md-6">
    <h2>Winkelwagen</h2>
    <?php if (!empty($cart)) { ?>
        <dl>
            <?php foreach ($cart as $product) : ?>
                <dt><?=$product->getTitle();?><!--<span class="pull-right"> stuks</span>--></dt>
                <dd><?=$product->getDescription();?></dd>
            <?php endforeach; ?>
        </dl>
    <?php } else { ?>
        <p>Er zitten geen producten in uw winkelwagen</p>
    <?php } ?>
    <a class="btn btn-default btn-sm" href="<?php echo $this->url('category',
        array('action'=>'clearSession'));?>">
        Winkelwagen legen
    </a>
    <a class="btn btn-success btn-sm" href="<?php echo $this->url('order',
        array('action'=>'index'));?>">
        Bestellen
    </a>
</div>