<?php
$title = 'Bestellingen';
$this->headTitle($title);
?>

<div class="col-md-6">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <h2>Winkelwagen</h2>
    <?php if (!empty($cart)) { ?>
        <dl>
            <?php foreach ($cart as $product) : ?>
                <dt><?=$product['title']?> <span class="pull-right"><?=$product['quantity']?> stuks</span></dt>
                <dd><?=$product['desc']?></dd>
            <?php endforeach; ?>
        </dl>
    <?php } else { ?>
        <p>Er zitten geen producten in uw winkelwagen</p>
    <?php } ?>
    <a class="btn btn-default btn-sm" href="<?php echo $this->url('category',
        array('action'=>'clearSession'));?>">
        Winkelwagen legen
    </a>
    <a class="btn btn-success btn-sm" href="<?php echo $this->url('cart',
        array('action'=>'order'));?>">
        Bestellen
    </a>
</div>