<?php
$title = 'Bestelling geplaatst';
$this->headTitle($title);
?>

<div class="col-md-12">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="alert alert-success">
        <p>Uw bestelling is succesvol geplaatst.</p>
        <p>
            Ordernummer: <?=$order->getId();?> <br>
            Prijs: &euro;<?=$order->getPrice();?> <br>
            Datum: <?=date_format($order->getDate(),"d-m-Y H:i:s");?>
        </p>
        <p>
            Uw gegevens:<br>
            <?=$customer->getFirstname();?> <?=$customer->getSurname();?><br>
            <?=$customer->getEmail();?> <br>
            <?=$customer->getAddress();?> <br>
            <?=$customer->getZipcode();?> <?=$customer->getCity();?><br>
        </p>
    </div>

</div>