<?php
$title = 'Bestellingen';
$this->headTitle($title);
?>

<div class="col-md-12">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php if (!empty($orders)) { ?>
        <?php foreach ($orders as $order) : ?>
            <dl class="dl-horizontal">
                <dt>
                    Ordernummer: <?=$order->getId();?> <br>
                    <?=date_format($order->getDate(),"d-m-Y H:i");?> <br>
                    Prijs: &euro;<?=$order->getPrice();?> <br></br>
                    <?=$order->getCustomer()->getFirstname();?> <?=$order->getCustomer()->getSurname();?> <br>
                    <?=$order->getCustomer()->getEmail();?> <br>
                    <?=$order->getCustomer()->getAddress();?> <br>
                    <?=$order->getCustomer()->getZipcode();?> <?=$order->getCustomer()->getCity();?><br>
                </dt>
                <dd>
                    <?php foreach($order->getHistory() as $orderhistory) {
                        echo '<strong>'.$orderhistory->getHistoryProduct()->getTitle().'</strong><br>';
                        echo $orderhistory->getHistoryProduct()->getDescription().'<br>';
                        echo 'Stukprijs: &euro;'.$orderhistory->getHistoryProduct()->getPrice().'<br>';
                        echo 'Aantal: '.$orderhistory->getQuantity().'<br></br>';
                    } ?>
                </dd>
            </dl>
            <hr>
        <?php endforeach; ?>
    <?php } else { ?>
        <p>Er zijn geen orders bekend</p>
    <?php } ?>
</div>